### ISSUE TITLE
Abstract over different return types of test method

### ISSUE THREAD

**Issue by tisonkun** [jbr/test-harness#37]
Hi @jbr! In the practices of test-harness, we make the following trait to abstract over different return types, namely `()` and `Result<T, E>`.

Here is the code and I suppose it might be useful to provide as a trait and deliver from within the upstream (i.e., test-harness).

```rust
pub trait Success {
    fn success() -> Self;
}

impl Success for () {
    fn success() -> Self {}
}

impl<T, E> Success for Result<T, E>
where
    T: Default,
{
    fn success() -> Self {
        Ok(Default::default())
    }
}
```

You make the final decision :D

**Comment by tisonkun** [comment]
It can be used as:

```rust
pub fn integration<T, Fut>(test: impl FnOnce(String, ObjectStoreProps) -> Fut) -> T
where
    T: Success,
    Fut: Future<Output = T>,
{ ... }
```

**Comment by jbr** [comment]
Would [`Termination`](https://doc.rust-lang.org/std/process/trait.Termination.html) work for your use case? That's how rust's test system is defined, and also test harness.

**Comment by tisonkun** [comment]
@jbr Cool! Good to know.

Now I write:

```rust
pub fn integration<T, Fut>(test: impl FnOnce(TestEnvProps) -> Fut) -> T
where
    T: std::process::Termination + Default,
    Fut: Future<Output = T>,
{
    if option_enabled("SKIP_INTEGRATION") {
        return Ok(T::default());
    }
}
```

Let me close this issue after my whole refactor done :D

**Comment by tisonkun** [comment]
Works well. Thank you!

**Comment by tisonkun** [comment]
Well .. A little bit issue: `Result` doesn't `impl Default` for `T: Default` so it's not quite easy to support skip by env.
